title: Alexander Greenhalgh
description: "PhD Student in Computer Science at Georgia Tech. Research in ML, scientific computing, and operations research."
url: "https://ahalgh.github.io"
baseurl: ""
image: "/images/Profile_Headshot.jpeg"

author:
  name: Alexander Greenhalgh
  email: agreenhalgh3@gatech.edu

markdown: kramdown
kramdown:
  input: GFM

collections:
  papers:
    output: true
    permalink: /papers/:name/

plugins:
  - jekyll-sitemap
